# Dahua_1_camera_parameter
image_width: 800
image_height: 600
camera_name: narrow_stereo
camera_matrix:
  rows: 3
  cols: 3
  data: [1744.625995825444,    0.     ,  404.74331,
            0.     , 1755.048845244444,  309.01202,
            0.     ,    0.     ,    1.     ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [-0.037503, 0.350149, -0.010575, -0.003105, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [1744.625995825444 ,    0.     ,          404.74331,    0.     ,
            0.     ,         1755.048845244444,   309.01202,    0.     ,
            0.     ,            0.     ,            1.00000,    0.     ]